- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: custom-source-extra-rules-1
    configMap:
      name: custom-source-extra-rules-1

- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    name: custom-source-extra-rules-1
    mountPath: /etc/kubernetes/node-feature-discovery/custom.d/extra-rules-1
    readOnly: true
