apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  runtimeClassName: nvidia
  containers:
    - name: cuda-test
      image: "nvidia/cuda:11.4.3-base-ubuntu20.04"
      command: ["nvidia-smi"]
      resources:
        limits:
          nvidia.com/gpu: 1
  restartPolicy: OnFailure
# See the output with kubectl logs gpu-test
