apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui
  namespace: open-webui
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
