---
apiVersion: v1
kind: Namespace
metadata:
  name: ollama
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
  labels:
    app: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
      - name: ollama
        image: docker.io/ollama/ollama:0.6.6
        ports:
        - containerPort: 11434
          name: http
        volumeMounts:
          - name: ollama
            mountPath: /root/.ollama
      volumes:
        - name: ollama
          persistentVolumeClaim:
            claimName: ollama
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: ollama
spec:
  type: LoadBalancer
  selector:
    app: ollama
  ports:
    - name: http
      port: 80
      targetPort: http
---
