#!/usr/bin/env python3

from argparse import ArgumentParser
from subprocess import run

def aptInstall(name):
    run(['apt', 'install', '-y', name])

def setupFirewall():
    # Regardless of how dynamic your network environment may be, it is still
    # useful to be familiar with the general idea behind each of the predefined
    # zones for firewalld. In order from least trusted to most trusted, the
    # predefined zones within firewalld are:
    # drop: Any incoming network packets are dropped, there is no reply. Only
    #       outgoing network connections are possible.
    # block: Any incoming network connections are rejected with an
    #        icmp-host-prohibited message for IPv4 and icmp6-adm-prohibited
    #        for IPv6. Only network connections initiated within this system
    #        are possible.
    # public: For use in public areas. You do not trust the other computers on
    #         networks to not harm your computer. Only selected incoming
    #         connections are accepted.
    # external: For use on external networks with IPv4 masquerading enabled
    #           especially for routers. You do not trust the other computers on
    #           networks to not harm your computer. Only selected incoming
    #           connections are accepted.
    # dmz: For computers in your demilitarized zone that are publicly-accessible
    #      with limited access to your internal network. Only selected incoming
    #      connections are accepted.
    # work: For use in work areas. You mostly trust the other computers on
    #       networks to not harm your computer. Only selected incoming
    #       connections are accepted.
    # home: For use in home areas. You mostly trust the other computers on
    #       networks to not harm your computer. Only selected incoming
    #       connections are accepted.
    # internal: For use on internal networks. You mostly trust the other
    #           computers on the networks to not harm your computer. Only
    #           selected incoming connections are accepted.
    # trusted: All network connections are accepted.
    # https://firewalld.org/documentation/zone/predefined-zones.html

    aptInstall('firewalld')

    def firewallCmd(args):
        run(['firewall-cmd', '--permanent'] + args)

    # By default, firewalld uses the public zone and has dhcpv6-client and ssh
    # services running. Disable these because we don't host these services on
    # PCs.
    firewallCmd(['--remove-service', 'dhcpv6-client'])
    firewallCmd(['--remove-service', 'ssh'])

if __name__ == '__main__':
    setupFirewall()
